### ISSUE TITLE
setEnabled and setVisible no addButton da TGrid

### ISSUE THREAD

**Issue by bjverde** [bjverde/formDin#205]
Criar as opções 
- setEnabled
- setVisible

addButton da TGrid (linha 1550) . Lembrando que usa um objeto do tipo TButton que herda do TControl que já tem os metodos.

**Comment by bjverde** [comment]
Possível mudança talvez seja apenas

```php
            $button = new TButton( $strName, $strRotulo, $strAction, $strOnClick, $strConfirmMessage, $strImage, $strImageDisabled, $strHint, $boolSubmitAction );
            $button->setEnabled();
            $button->setVisible();
```

**Comment by barbosa2305** [comment]
A alteração não se faz necessária, pois as propriedades funcionam como mostrado nos seguintes exemplos:
`$gride->addButton('Teste1', null, 'btnTeste1', null, null, null, null)->setVisible(false);`
`$gride->addButton('Teste2', null, 'btnTeste2', null, null, null, null)->setEnabled(false);`
