### ISSUE TITLE
Bug: A treeview não apresenta corretamente a visualização hierárquica de pastas, quando existem mais de 2 níveis.

### ISSUE THREAD

**Issue by barbosa2305** [bjverde/formDin#218]

**Comment by bjverde** [comment]
FormDin 4.8.2 novo menu.
App Exemplo v1.0. MENU > Containers > TreeView > Com vários níveis
![image](https://user-images.githubusercontent.com/1070062/75614272-c70a4000-5b15-11ea-8463-367ff0d85775.png)

**Comment by bjverde** [comment]
Está relacionado com #218

**Comment by bjverde** [comment]
No FormDin 4.22.0 o problema está resolvido 

![image](https://user-images.githubusercontent.com/1070062/213805862-ca162538-1005-4ec3-829e-ea6e4745a48e.png)
