### ISSUE TITLE
Bug: A imagem "carregando.gif" não está sumindo quando o resultado da paginação foi concluído.

### ISSUE THREAD

**Issue by barbosa2305** [bjverde/formDin#219]

**Comment by bjverde** [comment]
O Bug aconteceu entre a [v4.7.8](https://github.com/bjverde/formDin/releases/tag/v4.7.8) e [v4.8.0](https://github.com/bjverde/formDin/releases/tag/v4.8.0)

Pois não existia o problema na versão [v4.7.8](https://github.com/bjverde/formDin/releases/tag/v4.7.8)

**Comment by bjverde** [comment]
O Bug ocorreu no [commi fd243305fa171ec6f5df4bcf27777c5664035f77](https://github.com/bjverde/formDin/commit/fd243305fa171ec6f5df4bcf27777c5664035f77) pois o anterior não tinha o erro [commit d717799080dbdc837a48858dbcb61ff2a59dbf10](https://github.com/bjverde/formDin/commit/d717799080dbdc837a48858dbcb61ff2a59dbf10)
