### ISSUE TITLE
CSS: Grid - alinhamento do Label nas colunas

### ISSUE THREAD

**Issue by Cavalow** [bjverde/formDin#41]
Corrigir o  alinhamento do Label das colunas do Grid para alinhar sempre ao centro

![image](https://user-images.githubusercontent.com/33034978/37804803-f5daeb62-2e14-11e8-98fc-9ab98f84d609.png)

**Comment by bjverde** [comment]
Não será feito pois o espaço a direita é reservado para a seta da ordenação

![image](https://user-images.githubusercontent.com/1070062/60939807-73f62b00-a2af-11e9-87e4-3cb89069b2b8.png)

**Comment by Cavalow** [comment]
ontem eu vi, mude o label de quantidade pra Qtd.


Em qua, 10 de jul de 2019 às 01:10, Bjverde <notifications@github.com>
escreveu:

**Comment by Cavalow** [comment]
outra, o tamanho reservado do grid para a coluna tem que ser modificado por
causa do label


Em qui, 11 de jul de 2019 às 11:15, Raphael Cavalcante <
raphael.cavalcante@gmail.com> escreveu:
