### ISSUE TITLE
Campo memo contagem caracteres

### ISSUE THREAD

**Issue by bjverde** [bjverde/formDin#77]
A contagem de caracteres do campo memo não está correta. 
A contagem não considera os caracteres de fim de linha de retorno do carro.

**Comment by bjverde** [comment]
Possível relação

> Só para lembrar, no post passado, utilizamos o comando utf8_decode para consertar a contagem de caracteres com acentuação. Sem a utilização deste comando, o strlen() acabava contando letras acentuadas como 2 caracteres.

https://blog.dialhost.com.br/utf8_decode-e-utf8_encode-tratando-com-codificacao-unicode/

**Comment by Cavalow** [comment]
@tauvares vc que resolveu esta issue
