### ISSUE TITLE
Análise de Pontos de Função (APF) 

### ISSUE THREAD

**Issue by bjverde** [bjverde/formDin#93]
O formDin tem as funções, para fazer Análise de Pontos de Função (APF) . Descobrir como funciona os métodos 

TForm->processApf
TForm->processarApfFields

**Comment by bjverde** [comment]
@Cavalow o SysGen usa os Métodos da Classe TDAO para conhecer o modelo do banco de dados.

**Comment by bjverde** [comment]
Um dos erros é a falta do Spreadsheet_Excel_Writer

**Comment by Cavalow** [comment]
neste caso, acho que terminou ai


Em sex, 18 de jan de 2019 às 02:26, Bjverde <notifications@github.com>
escreveu:

**Comment by bjverde** [comment]
Problema fechado e deixado para o futuro
